version: '3.7'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
  backend:
    build:
      context: backend/user_micoService
      dockerfile: Dockerfile-backend
    ports:
      - 3000:3000